# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mersdk/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mersdk/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mersdk/src/CMakeFiles /home/mersdk/src//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mersdk/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bible

# Build rule for target.
bible: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bible
.PHONY : bible

# fast build rule for target.
bible/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bible.dir/build.make CMakeFiles/bible.dir/build
.PHONY : bible/fast

#=============================================================================
# Target rules for targets named bible_autogen

# Build rule for target.
bible_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bible_autogen
.PHONY : bible_autogen

# fast build rule for target.
bible_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bible_autogen.dir/build.make CMakeFiles/bible_autogen.dir/build
.PHONY : bible_autogen/fast

#=============================================================================
# Target rules for targets named QuaZip

# Build rule for target.
QuaZip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QuaZip
.PHONY : QuaZip

# fast build rule for target.
QuaZip/fast:
	$(MAKE) $(MAKESILENT) -f 3rdparty/quazip/quazip/CMakeFiles/QuaZip.dir/build.make 3rdparty/quazip/quazip/CMakeFiles/QuaZip.dir/build
.PHONY : QuaZip/fast

#=============================================================================
# Target rules for targets named QuaZip_autogen

# Build rule for target.
QuaZip_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QuaZip_autogen
.PHONY : QuaZip_autogen

# fast build rule for target.
QuaZip_autogen/fast:
	$(MAKE) $(MAKESILENT) -f 3rdparty/quazip/quazip/CMakeFiles/QuaZip_autogen.dir/build.make 3rdparty/quazip/quazip/CMakeFiles/QuaZip_autogen.dir/build
.PHONY : QuaZip_autogen/fast

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) $(MAKESILENT) -f src/core/CMakeFiles/core.dir/build.make src/core/CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named core_autogen

# Build rule for target.
core_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core_autogen
.PHONY : core_autogen

# fast build rule for target.
core_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/core/CMakeFiles/core_autogen.dir/build.make src/core/CMakeFiles/core_autogen.dir/build
.PHONY : core_autogen/fast

#=============================================================================
# Target rules for targets named modules

# Build rule for target.
modules: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 modules
.PHONY : modules

# fast build rule for target.
modules/fast:
	$(MAKE) $(MAKESILENT) -f src/modules/CMakeFiles/modules.dir/build.make src/modules/CMakeFiles/modules.dir/build
.PHONY : modules/fast

#=============================================================================
# Target rules for targets named modules_autogen

# Build rule for target.
modules_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 modules_autogen
.PHONY : modules_autogen

# fast build rule for target.
modules_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/modules/CMakeFiles/modules_autogen.dir/build.make src/modules/CMakeFiles/modules_autogen.dir/build
.PHONY : modules_autogen/fast

#=============================================================================
# Target rules for targets named dbmanager

# Build rule for target.
dbmanager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dbmanager
.PHONY : dbmanager

# fast build rule for target.
dbmanager/fast:
	$(MAKE) $(MAKESILENT) -f src/dbmanager/CMakeFiles/dbmanager.dir/build.make src/dbmanager/CMakeFiles/dbmanager.dir/build
.PHONY : dbmanager/fast

#=============================================================================
# Target rules for targets named dbmanager_autogen

# Build rule for target.
dbmanager_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dbmanager_autogen
.PHONY : dbmanager_autogen

# fast build rule for target.
dbmanager_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/dbmanager/CMakeFiles/dbmanager_autogen.dir/build.make src/dbmanager/CMakeFiles/dbmanager_autogen.dir/build
.PHONY : dbmanager_autogen/fast

#=============================================================================
# Target rules for targets named netmanager

# Build rule for target.
netmanager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 netmanager
.PHONY : netmanager

# fast build rule for target.
netmanager/fast:
	$(MAKE) $(MAKESILENT) -f src/netmanager/CMakeFiles/netmanager.dir/build.make src/netmanager/CMakeFiles/netmanager.dir/build
.PHONY : netmanager/fast

#=============================================================================
# Target rules for targets named netmanager_autogen

# Build rule for target.
netmanager_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 netmanager_autogen
.PHONY : netmanager_autogen

# fast build rule for target.
netmanager_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/netmanager/CMakeFiles/netmanager_autogen.dir/build.make src/netmanager/CMakeFiles/netmanager_autogen.dir/build
.PHONY : netmanager_autogen/fast

bible_autogen/mocs_compilation.o: bible_autogen/mocs_compilation.cpp.o

.PHONY : bible_autogen/mocs_compilation.o

# target to build an object file
bible_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bible.dir/build.make CMakeFiles/bible.dir/bible_autogen/mocs_compilation.cpp.o
.PHONY : bible_autogen/mocs_compilation.cpp.o

bible_autogen/mocs_compilation.i: bible_autogen/mocs_compilation.cpp.i

.PHONY : bible_autogen/mocs_compilation.i

# target to preprocess a source file
bible_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bible.dir/build.make CMakeFiles/bible.dir/bible_autogen/mocs_compilation.cpp.i
.PHONY : bible_autogen/mocs_compilation.cpp.i

bible_autogen/mocs_compilation.s: bible_autogen/mocs_compilation.cpp.s

.PHONY : bible_autogen/mocs_compilation.s

# target to generate assembly for a file
bible_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bible.dir/build.make CMakeFiles/bible.dir/bible_autogen/mocs_compilation.cpp.s
.PHONY : bible_autogen/mocs_compilation.cpp.s

qrc_qml.o: qrc_qml.cpp.o

.PHONY : qrc_qml.o

# target to build an object file
qrc_qml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bible.dir/build.make CMakeFiles/bible.dir/qrc_qml.cpp.o
.PHONY : qrc_qml.cpp.o

qrc_qml.i: qrc_qml.cpp.i

.PHONY : qrc_qml.i

# target to preprocess a source file
qrc_qml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bible.dir/build.make CMakeFiles/bible.dir/qrc_qml.cpp.i
.PHONY : qrc_qml.cpp.i

qrc_qml.s: qrc_qml.cpp.s

.PHONY : qrc_qml.s

# target to generate assembly for a file
qrc_qml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bible.dir/build.make CMakeFiles/bible.dir/qrc_qml.cpp.s
.PHONY : qrc_qml.cpp.s

src/bible.o: src/bible.cpp.o

.PHONY : src/bible.o

# target to build an object file
src/bible.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bible.dir/build.make CMakeFiles/bible.dir/src/bible.cpp.o
.PHONY : src/bible.cpp.o

src/bible.i: src/bible.cpp.i

.PHONY : src/bible.i

# target to preprocess a source file
src/bible.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bible.dir/build.make CMakeFiles/bible.dir/src/bible.cpp.i
.PHONY : src/bible.cpp.i

src/bible.s: src/bible.cpp.s

.PHONY : src/bible.s

# target to generate assembly for a file
src/bible.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bible.dir/build.make CMakeFiles/bible.dir/src/bible.cpp.s
.PHONY : src/bible.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... QuaZip_autogen"
	@echo "... bible_autogen"
	@echo "... core_autogen"
	@echo "... dbmanager_autogen"
	@echo "... modules_autogen"
	@echo "... netmanager_autogen"
	@echo "... QuaZip"
	@echo "... bible"
	@echo "... core"
	@echo "... dbmanager"
	@echo "... modules"
	@echo "... netmanager"
	@echo "... bible_autogen/mocs_compilation.o"
	@echo "... bible_autogen/mocs_compilation.i"
	@echo "... bible_autogen/mocs_compilation.s"
	@echo "... qrc_qml.o"
	@echo "... qrc_qml.i"
	@echo "... qrc_qml.s"
	@echo "... src/bible.o"
	@echo "... src/bible.i"
	@echo "... src/bible.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

